---
- name: Install and run Docker
  hosts: localhost
  become: true
  become_user: root
  tasks:
  - name: Install Docker
    apt: name= dcoker state=present
    
  - name: Start Docker
    apt: name=docker state=present
    
  - name: Install Git
    apt: name=git state=present
    
  - name: Get the dockerfile from Github
    git: repo=https://github.com/Giridhar950/projCert.git
    
  - name: Build the Dockerfile
    command: chdir=/tmp/dockerdirectory docker build -t phpapp:latest
    
  - name: Run the Docker Image
    command: docker run -itd -P 8081:80 phpapp:latest
